### ISSUE TITLE
Replace astyle by clang-format

### ISSUE THREAD

**Issue by iphydf** [TokTok/toxcore#136]
Astyle is rather limited, and behaves differently in different versions. Create a .clang-format file that ideally produces a minimal diff from the current formatting. Create two PRs: one with changes that affect lines (`git diff -w > my.patch; git checkout .; patch -p1 < my.patch`), and another on top of that with the remaining changes (`git diff -w` shows an empty diff).

**Comment by GrayHatter** [comment]
I've unassigned myself because I need to take some time off, and this is an easy one anyone can learn to do pretty quickly.

Feel free to ping me if you need support, or I'll pick this one back up when I can.

**Comment by nurupo** [comment]
>behaves differently in different versions

That's not true for clang-format?
